flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
resolver: lts-9.0
ghc-options:
  "*": -Wall -Wno-type-defaults -Wno-orphans -Wno-name-shadowing -Wno-missing-signatures -fprint-potential-instances
